module.exports = {
  apps: [
    {
      name: 'crypto-dashboard-web',
      cwd: __dirname,
      script: 'scripts/start-prod.mjs',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || '3000',
        HOSTNAME: process.env.HOSTNAME || '127.0.0.1',
        DISABLE_SCREENER_SCHEDULER: '1',
        SCREENER_STORAGE_MODE: 'file',
        SCREENER_STORAGE_BACKEND: 'file',
        SCREENER_REQUIRE_DATABASE: '0',
        SCREENER_FILE_MODE_STRICT: '1',
      },
      max_memory_restart: '768M',
      time: true,
      out_file: './logs/pm2-web-out.log',
      error_file: './logs/pm2-web-error.log',
      merge_logs: true,
    },
    {
      name: 'crypto-dashboard-screener',
      cwd: __dirname,
      script: 'scripts/screener/start.ts',
      interpreter: 'node_modules/.bin/tsx',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      env: {
        NODE_ENV: 'production',
        SCREENER_STORAGE_MODE: 'file',
        SCREENER_STORAGE_BACKEND: 'file',
        SCREENER_REQUIRE_DATABASE: '0',
        SCREENER_SYMBOLS: process.env.SCREENER_SYMBOLS || '',
        SCREENER_MAX_SYMBOLS: process.env.SCREENER_MAX_SYMBOLS || '100',
        SCREENER_MAX_CONCURRENT_SYMBOLS: process.env.SCREENER_MAX_CONCURRENT_SYMBOLS || '3',
        SCREENER_CANDLE_LIMIT: process.env.SCREENER_CANDLE_LIMIT || '120',
      },
      max_memory_restart: '512M',
      time: true,
      out_file: './logs/pm2-screener-out.log',
      error_file: './logs/pm2-screener-error.log',
      merge_logs: true,
    },
  ],
};
