#!/usr/bin/env bash
# Configure nginx + optional TLS for crypto-dashboard on a VPS.
#
# Usage:
#   sudo bash deploy/setup-domain.sh example.com
#   sudo bash deploy/setup-domain.sh example.com --www --tls you@example.com
#   sudo bash deploy/setup-domain.sh example.com --no-www
#
# Prerequisites: nginx installed; app already listening on 127.0.0.1:3000
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root: sudo bash deploy/setup-domain.sh <domain>" >&2
  exit 1
fi

DOMAIN="${1:-}"
if [ -z "${DOMAIN}" ] || [[ "${DOMAIN}" == -* ]]; then
  echo "Usage: sudo bash deploy/setup-domain.sh <domain> [--www] [--no-www] [--tls email@domain]" >&2
  exit 1
fi
shift || true

INCLUDE_WWW=1
TLS_EMAIL=""
APP_PORT="${APP_PORT:-3000}"
SITE_NAME="crypto-dashboard"
AVAILABLE="/etc/nginx/sites-available/${SITE_NAME}"
ENABLED="/etc/nginx/sites-enabled/${SITE_NAME}"

while [ $# -gt 0 ]; do
  case "$1" in
    --www) INCLUDE_WWW=1; shift ;;
    --no-www) INCLUDE_WWW=0; shift ;;
    --tls)
      TLS_EMAIL="${2:-}"
      if [ -z "${TLS_EMAIL}" ]; then
        echo "--tls requires an email for Let's Encrypt notices" >&2
        exit 1
      fi
      shift 2
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

if ! command -v nginx >/dev/null 2>&1; then
  apt-get update
  apt-get install -y nginx
fi

SERVER_NAMES="${DOMAIN}"
if [ "${INCLUDE_WWW}" -eq 1 ]; then
  SERVER_NAMES="${DOMAIN} www.${DOMAIN}"
fi

cat > "${AVAILABLE}" <<EOF
# Generated by deploy/setup-domain.sh — do not hand-edit without care.
# App: Next.js on 127.0.0.1:${APP_PORT}

upstream crypto_dashboard_web {
    server 127.0.0.1:${APP_PORT};
    keepalive 32;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${SERVER_NAMES};

    client_max_body_size 10m;

    # ACME challenge path (certbot)
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        default_type "text/plain";
        try_files \$uri =404;
    }

    location /_next/static/ {
        proxy_pass http://crypto_dashboard_web;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        proxy_pass http://crypto_dashboard_web;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}
EOF

ln -sfn "${AVAILABLE}" "${ENABLED}"

# Drop default site if it conflicts on :80
if [ -L /etc/nginx/sites-enabled/default ]; then
  rm -f /etc/nginx/sites-enabled/default
fi

nginx -t
systemctl enable nginx
systemctl reload nginx

echo "[domain] nginx site enabled for: ${SERVER_NAMES}"
echo "[domain] ensure DNS A/AAAA for ${DOMAIN} points to this VPS IP."

if [ -n "${TLS_EMAIL}" ]; then
  if ! command -v certbot >/dev/null 2>&1; then
    apt-get update
    apt-get install -y certbot python3-certbot-nginx
  fi

  CERTBOT_DOMAINS=(-d "${DOMAIN}")
  if [ "${INCLUDE_WWW}" -eq 1 ]; then
    CERTBOT_DOMAINS+=(-d "www.${DOMAIN}")
  fi

  certbot --nginx \
    --non-interactive \
    --agree-tos \
    --email "${TLS_EMAIL}" \
    --redirect \
    "${CERTBOT_DOMAINS[@]}"

  echo "[domain] TLS enabled via Let's Encrypt for ${SERVER_NAMES}"
else
  echo "[domain] HTTP only. Add TLS later:"
  echo "  sudo bash deploy/setup-domain.sh ${DOMAIN} --tls you@example.com"
fi

echo
echo "Verify:"
echo "  curl -I http://${DOMAIN}/"
if [ -n "${TLS_EMAIL}" ]; then
  echo "  curl -I https://${DOMAIN}/"
fi
